# Generated by scripts/package-manifests.mjs for hush 0.9.0 — do not edit.
class Hush < Formula
  desc "Envelope-encrypted team secrets your AI agent can use but never read"
  homepage "https://github.com/omarei-omoto/hush"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.9.0/hush-darwin-arm64"
      sha256 "5530990aada89c6bc8c82c17579f72c59067c4f3cb0258d8035033a07bec1121"
    end
    on_intel do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.9.0/hush-darwin-x64"
      sha256 "67b9354dcef2bd085de839b304377ca4fa4555011511ef5658215a3d81694339"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.9.0/hush-linux-arm64"
      sha256 "3db8ad1b2546ef5d78e3e37ff7c9b3d57084ea3625d5fe61dda733fc7ffeb214"
    end
    on_intel do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.9.0/hush-linux-x64"
      sha256 "b13a44852dad878c23c0c3073b93954ef7b0c0466383bbe45c259b2f4e17dde7"
    end
  end

  def install
    bin.install Dir["hush-*"].first => "hush"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/hush --version").strip
  end
end
