# Generated by scripts/package-manifests.mjs for hush 0.11.1 — do not edit.
class Hush < Formula
  desc "Envelope-encrypted team secrets your AI agent can use but never read"
  homepage "https://github.com/omarei-omoto/hush"
  version "0.11.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.11.1/hush-darwin-arm64"
      sha256 "b07788a7886d4b9ded900ac1cab6d03785e523f5acd39681a6f12810d4096579"
    end
    on_intel do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.11.1/hush-darwin-x64"
      sha256 "f80ec66f779c1f4ff5b674f731a89927ae7024615d78724d45454fac37be2683"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.11.1/hush-linux-arm64"
      sha256 "fb6a0028d237bb5c694dccf534cf0e0b737a248fbb66b0d56b60decdc08020db"
    end
    on_intel do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.11.1/hush-linux-x64"
      sha256 "61c32d19192853e8e5592899b24f66df1a390699401db8c9eea61cd0825637da"
    end
  end

  def install
    bin.install Dir["hush-*"].first => "hush"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/hush --version").strip
  end
end
