# Generated by scripts/package-manifests.mjs for hush 0.12.0 — do not edit.
class Hush < Formula
  desc "Envelope-encrypted team secrets your AI agent can use but never read"
  homepage "https://github.com/omarei-omoto/hush"
  version "0.12.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.12.0/hush-darwin-arm64"
      sha256 "9d3f696d6f02b0eef35c0b103e355f3f5c27b338a61e2c8f0983f2186d30b849"
    end
    on_intel do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.12.0/hush-darwin-x64"
      sha256 "eed5f6fa9bbce57e2edf7494611ff30623c28dbadf6f1d66f70a543a5adc1db0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.12.0/hush-linux-arm64"
      sha256 "e67b6e9b933cd33c792be0666a7bd99eebc2ab51f6f92f19f1deccb3f2e542b3"
    end
    on_intel do
      url "https://github.com/omarei-omoto/hush/releases/download/v0.12.0/hush-linux-x64"
      sha256 "0519472dc280706d322c8c59c441cd0b7430f29eb8fa061bcb421bd3b897697b"
    end
  end

  def install
    bin.install Dir["hush-*"].first => "hush"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/hush --version").strip
  end
end
